# Generated by Django 5.0.6 on 2026-09-09 09:09

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, max_length=160, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Появился')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Как различать точки клиента, напр. «Кафе на набережной»', max_length=160, verbose_name='Точка')),
                ('domain', models.CharField(blank=True, help_text='Напр. moyokafe.padacha.ru', max_length=200, verbose_name='Домен')),
                ('license_key', models.CharField(default=billing.models.new_license_key, help_text='Кладётся в LICENSE_KEY в .env инстанса. Он же — секрет подписи ответов лицензии.', max_length=64, unique=True, verbose_name='Ключ лицензии')),
                ('plan', models.CharField(choices=[('start', 'Старт'), ('hall', 'Зал'), ('max', 'Максимум')], default='start', max_length=8, verbose_name='Тариф')),
                ('paid_until', models.DateField(default=billing.models.trial_end, help_text='Новая точка получает неделю бесплатно', verbose_name='Оплачено до')),
                ('grace_days', models.PositiveSmallIntegerField(default=7, help_text='Сколько дней после «оплачено до» точка ещё работает', verbose_name='Грейс, дней')),
                ('is_internal', models.BooleanField(default=False, help_text='Наше заведение: не биллится и никогда не блокируется', verbose_name='Своя точка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключена')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Выходила на связь')),
                ('last_version', models.CharField(blank=True, max_length=40, verbose_name='Версия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='billing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'ordering': ['client__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('months', models.PositiveSmallIntegerField(default=1, verbose_name='Месяцев')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.instance', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
